### ISSUE TITLE
trouble with Chrome only = Cannot read property '__e3_' of null

### ISSUE THREAD

**Issue by mjpaquet** [GoogleWebComponents/google-map#121]
my code work on IE and Firefox but i got this exception on Chrome

Exception caught during observer callback: TypeError: Cannot read property '__e3_' of null
    at Ue (https://maps.gstatic.com/maps-api-v3/api/js/20/6/intl/fr_ALL/main.js:16:1197)
    at new Se (https://maps.gstatic.com/maps-api-v3/api/js/20/6/intl/fr_ALL/main.js:19:321)
    at Object.R.addListener (https://maps.gstatic.com/maps-api-v3/api/js/20/6/intl/fr_ALL/main.js:16:915)
    at google-map-marker.Polymer._forwardEvent (http://localhost/bower_components/google-map/google-map.html:322:51)
    at google-map-marker.Polymer.clickEventsChanged (http://localhost/bower_components/google-map/google-map.html:221:18)
    at google-map-marker.properties.invokeMethod (http://localhost/bower_components/polymer/polymer.js:9385:12)
    at google-map-marker.properties.notifyPropertyChanges (http://localhost/bower_components/polymer/polymer.js:9374:20)
    at Object.Observer.report_ (http://localhost/bower_components/polymer/polymer.js:4913:24)
    at Object.createObject.check_ (http://localhost/bower_components/polymer/polymer.js:5319:12)
    at callback (http://localhost/bower_components/polymer/polymer.js:4811:20)

**Comment by ebidel** [comment]
You'll need to provide a working code snippet of your app. It's hard to say the cause from a stacktrace.

**Comment by mjpaquet** [comment]
my HTML :
<div fit style="bottom:64px;">
    <google-map fitToMarkers disableDefaultUI zoom="15">
        <template repeat="{{dataModel as point}}">
            <google-map-marker
                clickEvents="true"
                latitude="{{point.latitude}}"
                longitude="{{point.longitude}}"
                icon="http://www.googlemapsmarkers.com/v1/{{point.id}}/{{colorHexaBG[point.type]}}/222222/333333/"
                draggable="false"
                title="{{point.nom}}"></google-map-marker>
        </template>
    </google-map>
</div>


My JS :
Polymer('mainapp-element', {
            
    ready: function() {
        var ref = this;

        this.addEventListener('google-map-marker-click', function(mapEvent) {
            var title = mapEvent.path[0].title;
            var latitude = mapEvent.path[0].latitude;
            var longitude = mapEvent.path[0].longitude;
            ref.pinTouched(title, latitude, longitude);
        });

        var ajax = this.shadowRoot.querySelector("#ajaxGetPoint");

        var toggle = this.shadowRoot.querySelector('.culturel');
        toggle.addEventListener('change', function(){
            ref.dataModel = null;
            ref.shadowRoot.querySelector("google-map").clear();
            ajax.go();
        });

        toggle = this.shadowRoot.querySelector('.religieux');
        toggle.addEventListener('change', function(){
            ref.dataModel = null;
            ref.shadowRoot.querySelector("google-map").clear();
            ajax.go();
        });

        toggle = this.shadowRoot.querySelector('.architecture');
        toggle.addEventListener('change', function(){
            ref.dataModel = null;
            ref.shadowRoot.querySelector("google-map").clear();
            ajax.go();
        });

        ajax.go();
    }
});

**Comment by ebidel** [comment]
How about a working jsbin?

**Comment by mjpaquet** [comment]
i have clean my code as possible

http://jsbin.com/bamewi/12/edit?html,output

**Comment by mjpaquet** [comment]
if i remove clickEvents="true" from <google-map-marker> everything work again.

**Comment by DracoNoir** [comment]
I have a fix for this in pull request #123.

**Comment by mjpaquet** [comment]
working correctly now. thx
